name: release-ruby

on:
  push:
    branches: [ "main" ]

jobs:
  release-please:
    name: Build + Publish
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: google-github-actions/release-please-action@v4
      id: release
      with:
        release-type: ruby
        package-name: addons-api
        bump-minor-pre-major: true
        version-file: "lib/addons-api/version.rb"
    
    # Checkout code if release was created
    - uses: actions/checkout@v3
      if: ${{ steps.release.outputs.release_created }}
    
    # Set up Ruby if a release was created
    - name: Set up Ruby 3.2
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.2
      if: ${{ steps.release.outputs.release_created }}
    
    # Bundle install if a release was created
    - run: bundle install
      if: ${{ steps.release.outputs.release_created }}
    
    # Publish to RubyGems if a release was created
    - name: Publish to RubyGems
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBYGEMS_AUTH_TOKEN}}"
      if: ${{ steps.release.outputs.release_created }}
